In [2]:
import pandas as pd

In [3]:
products = pd.read_csv("product_info.csv")
products.head()

,product_id,product_name,brand_id,brand_name,loves_count,rating,reviews,size,variation_type,variation_value,...,online_only,out_of_stock,sephora_exclusive,highlights,primary_category,secondary_category,tertiary_category,child_count,child_max_price,child_min_price
0,P473671,Fragrance Discovery Set,6342,19-69,6320,3.6364,11.0,NaN,NaN,NaN,...,1,0,0,"['Unisex/ Genderless Scent', 'Warm &Spicy Scen...",Fragrance,Value & Gift Sets,Perfume Gift Sets,0,NaN,NaN
1,P473668,La Habana Eau de Parfum,6342,19-69,3827,4.1538,13.0,3.4 oz/ 100 mL,Size + Concentration + Formulation,3.4 oz/ 100 mL,...,1,0,0,"['Unisex/ Genderless Scent', 'Layerable Scent'...",Fragrance,Women,Perfume,2,85.0,30.0
2,P473662,Rainbow Bar Eau de Parfum,6342,19-69,3253,4.2500,16.0,3.4 oz/ 100 mL,Size + Concentration + Formulation,3.4 oz/ 100 mL,...,1,0,0,"['Unisex/ Genderless Scent', 'Layerable Scent'...",Fragrance,Women,Perfume,2,75.0,30.0
3,P473660,Kasbah Eau de Parfum,6342,19-69,3018,4.4762,21.0,3.4 oz/ 100 mL,Size + Concentration + Formulation,3.4 oz/ 100 mL,...,1,0,0,"['Unisex/ Genderless Scent', 'Layerable Scent'...",Fragrance,Women,Perfume,2,75.0,30.0
4,P473658,Purple Haze Eau de Parfum,6342,19-69,2691,3.2308,13.0,3.4 oz/ 100 mL,Size + Concentration + Formulation,3.4 oz/ 100 mL,...,1,0,0,"['Unisex/ Genderless Scent', 'Layerable Scent'...",Fragrance,Women,Perfume,2,75.0,30.0

In [4]:
products.info()
products.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8494 entries, 0 to 8493
Data columns (total 27 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   product_id          8494 non-null   object
 1   product_name        8494 non-null   object
 2   brand_id            8494 non-null   int64
 3   brand_name          8494 non-null   object
 4   loves_count         8494 non-null   int64
 5   rating              8216 non-null   float64
 6   reviews             8216 non-null   float64
 7   size                6863 non-null   object
 8   variation_type      7050 non-null   object
 9   variation_value     6896 non-null   object
 10  variation_desc      1250 non-null   object
 11  ingredients         7549 non-null   object
 12  price_usd           8494 non-null   float64
 13  value_price_usd     451 non-null    float64
 14  sale_price_usd      270 non-null    float64
 15  limited_edition     8494 non-null   int64
 16  new                 8494 non-null   int64
 17  online_only         8494 non-null   int64
 18  out_of_stock        8494 non-null   int64
 19  sephora_exclusive   8494 non-null   int64
 20  highlights          6287 non-null   object
 21  primary_category    8494 non-null   object
 22  secondary_category  8486 non-null   object
 23  tertiary_category   7504 non-null   object
 24  child_count         8494 non-null   int64
 25  child_max_price     2754 non-null   float64
 26  child_min_price     2754 non-null   float64
dtypes: float64(7), int64(8), object(12)
memory usage: 1.7+ MB

product_id               0
product_name             0
brand_id                 0
brand_name               0
loves_count              0
rating                 278
reviews                278
size                  1631
variation_type        1444
variation_value       1598
variation_desc        7244
ingredients            945
price_usd                0
value_price_usd       8043
sale_price_usd        8224
limited_edition          0
new                      0
online_only              0
out_of_stock             0
sephora_exclusive        0
highlights            2207
primary_category         0
secondary_category       8
tertiary_category      990
child_count              0
child_max_price       5740
child_min_price       5740
dtype: int64

In [5]:
products.describe(include='all')

,product_id,product_name,brand_id,brand_name,loves_count,rating,reviews,size,variation_type,variation_value,...,online_only,out_of_stock,sephora_exclusive,highlights,primary_category,secondary_category,tertiary_category,child_count,child_max_price,child_min_price
count,8494,8494,8494.000000,8494,8.494000e+03,8216.000000,8216.000000,6863,7050,6896,...,8494.000000,8494.000000,8494.000000,6287,8494,8486,7504,8494.000000,2754.000000,2754.000000
unique,8494,8415,NaN,304,NaN,NaN,NaN,2055,7,2729,...,NaN,NaN,NaN,4417,9,41,118,NaN,NaN,NaN
top,P473671,Fragrance Discovery Set,NaN,SEPHORA COLLECTION,NaN,NaN,NaN,1.7 oz/ 50 mL,Size,1.7 oz/ 50 mL,...,NaN,NaN,NaN,"['Layerable Scent', 'Floral Scent']",Skincare,Women,Perfume,NaN,NaN,NaN
freq,1,3,NaN,352,NaN,NaN,NaN,500,4043,374,...,NaN,NaN,NaN,64,2420,875,568,NaN,NaN,NaN
mean,NaN,NaN,5422.440546,NaN,2.917957e+04,4.194513,448.545521,NaN,NaN,NaN,...,0.219096,0.073699,0.279374,NaN,NaN,NaN,NaN,1.631622,53.792023,39.665802
std,NaN,NaN,1709.595957,NaN,6.609212e+04,0.516694,1101.982529,NaN,NaN,NaN,...,0.413658,0.261296,0.448718,NaN,NaN,NaN,NaN,5.379470,58.765894,38.685720
min,NaN,NaN,1063.000000,NaN,0.000000e+00,1.000000,1.000000,NaN,NaN,NaN,...,0.000000,0.000000,0.000000,NaN,NaN,NaN,NaN,0.000000,3.000000,3.000000
25%,NaN,NaN,5333.000000,NaN,3.758000e+03,3.981725,26.000000,NaN,NaN,NaN,...,0.000000,0.000000,0.000000,NaN,NaN,NaN,NaN,0.000000,22.000000,19.000000
50%,NaN,NaN,6157.500000,NaN,9.880000e+03,4.289350,122.000000,NaN,NaN,NaN,...,0.000000,0.000000,0.000000,NaN,NaN,NaN,NaN,0.000000,32.000000,28.000000
75%,NaN,NaN,6328.000000,NaN,2.684125e+04,4.530525,418.000000,NaN,NaN,NaN,...,0.000000,0.000000,1.000000,NaN,NaN,NaN,NaN,1.000000,59.000000,42.000000
max,NaN,NaN,8020.000000,NaN,1.401068e+06,5.000000,21281.000000,NaN,NaN,NaN,...,1.000000,1.000000,1.000000,NaN,NaN,NaN,NaN,105.000000,570.000000,400.000000

In [6]:
import glob

review_files = glob.glob("reviews_*.csv")
review_files

['reviews_0-250.csv',
 'reviews_1250-end.csv',
 'reviews_250-500.csv',
 'reviews_500-750.csv',
 'reviews_750-1250.csv']

In [7]:
reviews_list = []

for file in review_files:
    df = pd.read_csv(file, engine='python')
    reviews_list.append(df)

In [8]:
reviews = pd.concat(reviews_list, ignore_index=True)
reviews.head()

,Unnamed: 0,author_id,rating,is_recommended,helpfulness,total_feedback_count,total_neg_feedback_count,total_pos_feedback_count,submission_time,review_text,review_title,skin_tone,eye_color,skin_type,hair_color,product_id,product_name,brand_name,price_usd
0,0,1741593524,5,1.0,1.0,2,0,2,2023-02-01,I use this with the Nudestix “Citrus Clean Bal...,Taught me how to double cleanse!,NaN,brown,dry,black,P504322,Gentle Hydra-Gel Face Cleanser,NUDESTIX,19.0
1,1,31423088263,1,0.0,NaN,0,0,0,2023-03-21,I bought this lip mask after reading the revie...,Disappointed,NaN,NaN,NaN,NaN,P420652,Lip Sleeping Mask Intense Hydration with Vitam...,LANEIGE,24.0
2,2,5061282401,5,1.0,NaN,0,0,0,2023-03-21,My review title says it all! I get so excited ...,New Favorite Routine,light,brown,dry,blonde,P420652,Lip Sleeping Mask Intense Hydration with Vitam...,LANEIGE,24.0
3,3,6083038851,5,1.0,NaN,0,0,0,2023-03-20,I’ve always loved this formula for a long time...,Can't go wrong with any of them,NaN,brown,combination,black,P420652,Lip Sleeping Mask Intense Hydration with Vitam...,LANEIGE,24.0
4,4,47056667835,5,1.0,NaN,0,0,0,2023-03-20,"If you have dry cracked lips, this is a must h...",A must have !!!,light,hazel,combination,NaN,P420652,Lip Sleeping Mask Intense Hydration with Vitam...,LANEIGE,24.0

In [9]:
reviews.shape

(1094411, 19)

In [10]:
reviews.isnull().sum()

Unnamed: 0                       0
author_id                        0
rating                           0
is_recommended              167988
helpfulness                 561592
total_feedback_count             0
total_neg_feedback_count         0
total_pos_feedback_count         0
submission_time                  0
review_text                   1444
review_title                310654
skin_tone                   170539
eye_color                   209628
skin_type                   111557
hair_color                  226768
product_id                       0
product_name                     0
brand_name                       0
price_usd                        0
dtype: int64

In [11]:
products = products.drop_duplicates(subset="product_id")
products.shape

(8494, 27)

In [12]:
products.columns

Index(['product_id', 'product_name', 'brand_id', 'brand_name', 'loves_count',
       'rating', 'reviews', 'size', 'variation_type', 'variation_value',
       'variation_desc', 'ingredients', 'price_usd', 'value_price_usd',
       'sale_price_usd', 'limited_edition', 'new', 'online_only',
       'out_of_stock', 'sephora_exclusive', 'highlights', 'primary_category',
       'secondary_category', 'tertiary_category', 'child_count',
       'child_max_price', 'child_min_price'],
      dtype='object')

In [13]:
products["price_usd"].head()

0     35.0
1    195.0
2    195.0
3    195.0
4    195.0
Name: price_usd, dtype: float64

In [14]:
products["price_usd"].isnull().sum()

0

In [15]:
products["reviews"] = products["reviews"].fillna(0).astype(int)

In [16]:
products["value_price_usd"] = products["value_price_usd"].fillna(0)

In [17]:
products["sale_price_usd"] = products["sale_price_usd"].fillna(products['price_usd'])

In [18]:
products["secondary_category"] = products["secondary_category"].fillna("Unknown")
products["tertiary_category"] = products["tertiary_category"].fillna("Unknown")

In [19]:
reviews["is_recommended"] = reviews["is_recommended"].fillna(0).astype(int)

In [20]:
reviews = reviews.dropna(subset=["review_text"])

In [21]:
user_cols = ["skin_tone", "eye_color", "skin_type", "hair_color"]
reviews[user_cols] = reviews[user_cols].fillna("Unknown")

In [22]:
brand_map = products.set_index("product_id")["brand_name"]
price_map = products.set_index("product_id")["price_usd"]

reviews["brand_name"] = reviews["brand_name"].fillna(
    reviews["product_id"].map(brand_map)
)

reviews["price_usd"] = reviews["price_usd"].fillna(
    reviews["product_id"].map(price_map)
)

In [23]:
reviews.isnull().sum()

Unnamed: 0                       0
author_id                        0
rating                           0
is_recommended                   0
helpfulness                 560595
total_feedback_count             0
total_neg_feedback_count         0
total_pos_feedback_count         0
submission_time                  0
review_text                      0
review_title                309210
skin_tone                        0
eye_color                        0
skin_type                        0
hair_color                       0
product_id                       0
product_name                     0
brand_name                       0
price_usd                        0
dtype: int64

In [24]:
products.isnull().sum()

product_id               0
product_name             0
brand_id                 0
brand_name               0
loves_count              0
rating                 278
reviews                  0
size                  1631
variation_type        1444
variation_value       1598
variation_desc        7244
ingredients            945
price_usd                0
value_price_usd          0
sale_price_usd           0
limited_edition          0
new                      0
online_only              0
out_of_stock             0
sephora_exclusive        0
highlights            2207
primary_category         0
secondary_category       0
tertiary_category        0
child_count              0
child_max_price       5740
child_min_price       5740
dtype: int64

In [25]:
import numpy as np

In [26]:
products[['price_usd', 'sale_price_usd']].head(10)

   price_usd  sale_price_usd
0       35.0            35.0
1      195.0           195.0
2      195.0           195.0
3      195.0           195.0
4      195.0           195.0
5       30.0            30.0
6       30.0            30.0
7      195.0           195.0
8      195.0           195.0
9       30.0            30.0

In [27]:
products["effective_price_usd"] = products["sale_price_usd"].fillna(
    products["price_usd"]
)

In [28]:
products['discount_percentage'] = np.where(products['price_usd'] > 0,
 ((products['price_usd'] - products['effective_price_usd'] )/ products['price_usd']) * 100,
 0)

In [29]:
products['discount_percentage'] = products['discount_percentage'].round(2)

In [30]:
products['discount_percentage'].describe()

count    8494.000000
mean        1.368105
std         7.918790
min         0.000000
25%         0.000000
50%         0.000000
75%         0.000000
max        80.000000
Name: discount_percentage, dtype: float64

In [31]:
products.loc[products["discount_percentage"] > 0, "discount_percentage"].describe()

count    270.000000
mean      43.039556
std       13.402815
min        0.050000
25%       34.210000
50%       50.000000
75%       50.000000
max       80.000000
Name: discount_percentage, dtype: float64

In [32]:
products["discount_bucket"] = pd.cut(
    products["discount_percentage"],
    bins=[-0.1, 0.01, 10, 20, 30, 50, 100],
    labels=["No Discount", "<10%", "10–20%", "20–30%", "30–50%", "50%+"],
    right=True
)

In [33]:
products['discount_bucket'].head()

0    No Discount
1    No Discount
2    No Discount
3    No Discount
4    No Discount
Name: discount_bucket, dtype: category
Categories (6, object): ['No Discount' < '<10%' < '10–20%' < '20–30%' < '30–50%' < '50%+']

In [34]:
products[products["discount_percentage"] > 70][
    ["brand_name", "product_name", "price_usd", "sale_price_usd", "discount_percentage"]
].head()

,brand_name,product_name,price_usd,sale_price_usd,discount_percentage
499,beautyblender,BOUNCE Airbrush Liquid Whip Concealer,26.0,6.0,76.92
6478,SEPHORA COLLECTION,Cream Lip Shine Liquid Lipstick,15.0,3.0,80.00
6757,SEPHORA COLLECTION,Double-Ended Textured Facial Roller,24.0,6.0,75.00
7730,TOCCA,Gia,27.0,8.0,70.37
7732,TOCCA,Giulietta Rollerball,27.0,8.0,70.37

In [37]:
products["on_sale"] = (products["discount_percentage"] > 0).astype(int)

In [38]:
products["on_sale"].head()

0    0
1    0
2    0
3    0
4    0
Name: on_sale, dtype: int32

In [39]:
labels = ['Low', 'Medium', 'High']
products['popularity'] = pd.qcut(products['loves_count'], q=3, labels=labels)

In [40]:
products[['loves_count', 'popularity']].head(20)

    loves_count popularity
0          6320     Medium
1          3827        Low
2          3253        Low
3          3018        Low
4          2691        Low
5          2448        Low
6          1619        Low
7          1542        Low
8          1542        Low
9          1377        Low
10         1371        Low
11         1206        Low
12          981        Low
13          721        Low
14        19028       High
15         7526     Medium
16         3741        Low
17         3392        Low
18         4493        Low
19         3118        Low

In [41]:
reviews['rating'].head()

0    5
1    1
2    5
3    5
4    5
Name: rating, dtype: int64

In [42]:
labels = ['Underperforming', 'Satisfactory', 'High Rated']
products['rating_category'] = pd.qcut(products['rating'], q=3, labels=labels)

In [43]:
products[['popularity','rating_category']].head()

  popularity  rating_category
0     Medium  Underperforming
1        Low     Satisfactory
2        Low     Satisfactory
3        Low       High Rated
4        Low  Underperforming

In [44]:
products["price_range"] = pd.cut(
    products["price_usd"],
    bins=[0, 25, 50, 100, 200, 1000],
    labels=["<25", "25-50", "50-100", "100-200", "200+"]
)

In [45]:
products[['price_usd', 'price_range']].head(10)

   price_usd price_range
0       35.0       25-50
1      195.0     100-200
2      195.0     100-200
3      195.0     100-200
4      195.0     100-200
5       30.0       25-50
6       30.0       25-50
7      195.0     100-200
8      195.0     100-200
9       30.0       25-50

In [46]:
products["has_reviews"] = (products["reviews"] > 0).astype(int)

In [47]:
products[['reviews', 'has_reviews']].head()

   reviews  has_reviews
0       11            1
1       13            1
2       16            1
3       21            1
4       13            1

In [48]:
%pip install sqlalchemy psycopg2

Requirement already satisfied: sqlalchemy in c:\users\marys\appdata\local\programs\python\python311\lib\site-packages (2.0.41)
Requirement already satisfied: psycopg2 in c:\users\marys\appdata\local\programs\python\python311\lib\site-packages (2.9.11)
Requirement already satisfied: greenlet>=1 in c:\users\marys\appdata\local\programs\python\python311\lib\site-packages (from sqlalchemy) (3.2.2)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\marys\appdata\local\programs\python\python311\lib\site-packages (from sqlalchemy) (4.14.1)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.1.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [49]:
from sqlalchemy import create_engine

engine = create_engine('postgresql://postgres:marysia123@localhost:5432/sephora_project')

products.to_sql('dim_products', engine, if_exists='replace', index=False)

reviews.to_sql('fact_reviews', engine, if_exists='replace', index=False)

967

In [50]:
products.to_csv('cleaned_products.csv', index=False)
reviews.to_csv('cleaned_reviews.csv', index=False)

In [51]:
cleaned_products = pd.read_csv('cleaned_products.csv')
cleaned_reviews = pd.read_csv('cleaned_reviews.csv')

C:\Users\marys\AppData\Local\Temp\ipykernel_20524\455900835.py:2: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  cleaned_reviews = pd.read_csv('cleaned_reviews.csv')

In [52]:
cleaned_products.columns

Index(['product_id', 'product_name', 'brand_id', 'brand_name', 'loves_count',
       'rating', 'reviews', 'size', 'variation_type', 'variation_value',
       'variation_desc', 'ingredients', 'price_usd', 'value_price_usd',
       'sale_price_usd', 'limited_edition', 'new', 'online_only',
       'out_of_stock', 'sephora_exclusive', 'highlights', 'primary_category',
       'secondary_category', 'tertiary_category', 'child_count',
       'child_max_price', 'child_min_price', 'effective_price_usd',
       'discount_percentage', 'discount_bucket', 'on_sale', 'popularity',
       'rating_category', 'price_range', 'has_reviews'],
      dtype='object')

In [53]:
cleaned_reviews.columns

Index(['Unnamed: 0', 'author_id', 'rating', 'is_recommended', 'helpfulness',
       'total_feedback_count', 'total_neg_feedback_count',
       'total_pos_feedback_count', 'submission_time', 'review_text',
       'review_title', 'skin_tone', 'eye_color', 'skin_type', 'hair_color',
       'product_id', 'product_name', 'brand_name', 'price_usd'],
      dtype='object')